# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/sailfish/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    aboot \
    apdp \
    bootlocker \
    cmnlib32 \
    cmnlib64 \
    devcfg \
    hosd \
    hyp \
    keymaster \
    modem \
    pmic \
    rpm \
    tz \
    xbl
